### ISSUE TITLE
my project have four 'HEAD_CLS_NAME',and how to modify the code to run success in program,expecially the postprocess.cu;  

### ISSUE THREAD

**Issue by qiuhui1991** [hova88/PointPillars_MultiHead_40FPS#10]
RPN_HEAD_CFGS: [
            {
                'HEAD_CLS_NAME': [ 'vehicle' ],
            },
            {
                'HEAD_CLS_NAME': [ 'car' ],
            },
            {
                'HEAD_CLS_NAME': [ 'pedestrian'],
            },
            {
                'HEAD_CLS_NAME': [ 'cyclist' ],
            },
        ]

**Comment by hova88** [comment]
> RPN_HEAD_CFGS: [
> {
> 'HEAD_CLS_NAME': [ 'vehicle' ],
> },
> {
> 'HEAD_CLS_NAME': [ 'car' ],
> },
> {
> 'HEAD_CLS_NAME': [ 'pedestrian'],
> },
> {
> 'HEAD_CLS_NAME': [ 'cyclist' ],
> },
> ]

这个说起来有点复杂，而且我写的`postprocess.cu`还有很多冗余和不足的地方，你可以看看apollo或者autoware的postprocess部分，他们是singlehead的，对比这我这个，你可以设计一个符合自己需求的后处理单元。

**Comment by qiuhui1991** [comment]
> > RPN_HEAD_CFGS: [
> > {
> > 'HEAD_CLS_NAME': [ 'vehicle' ],
> > },
> > {
> > 'HEAD_CLS_NAME': [ 'car' ],
> > },
> > {
> > 'HEAD_CLS_NAME': [ 'pedestrian'],
> > },
> > {
> > 'HEAD_CLS_NAME': [ 'cyclist' ],
> > },
> > ]
> 
> 这个说起来有点复杂，而且我写的`postprocess.cu`还有很多冗余和不足的地方，你可以看看apollo或者autoware的postprocess部分，他们是singlehead的，对比这我这个，你可以设计一个符合自己需求的后处理单元。

谢谢
