### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by ycdhqzhiai** [hova88/PointPillars_MultiHead_40FPS#14]
在cmake时候报错
```shell
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
NVINFER
```

**Comment by hova88** [comment]
把报错打印的全面一点

**Comment by speshowBUAA** [comment]
更新cmake版本至3.17

**Comment by hova88** [comment]
> 在cmake时候报错
> 
> ```shell
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> NVINFER
> ```



> 更新cmake版本至3.17

updated.
