### ISSUE TITLE
Cmake Error

### ISSUE THREAD

**Issue by cagik** [hova88/PointPillars_MultiHead_40FPS#15]
您好，我在执行 `cmake ..`  时，产生以下错误

```
Building tests
-- 

-- BUILD SUMMARY
--   CMAKE_GENERATOR      : Unix Makefiles
--   Compiler ID          : GNU
--   Build type           : Release
--   Build shared libs    : ON
--   Use double for kernel: OFF

--   Build tests          : ON
-- 

-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
NVINFER
    linked by target "pointpillars" in directory /home/cavata/project/OpenPCDet/PointPillars_MultiHead_40FPS/pointpillars
    linked by target "test_model" in directory /home/cavata/project/OpenPCDet/PointPillars_MultiHead_40FPS/test

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

请问您是否有相应的解决方案，十分感谢！

**Comment by hova88** [comment]
可能没装gtest？我不确定，需要你把问题打的更全一些

**Comment by cagik** [comment]
我在安装Google-test后仍然存在cmake error

```
(openpcdet) cavata@cavata:~/project/OpenPCDet/PointPillars_MutilHead_40FPS/build $ cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
Building tests
-- Found Python: /home/cavata/anaconda3/envs/openpcdet/bin/python3.7 (found version "3.7.10") found components: Interpreter 
-- 
-- BUILD SUMMARY
--   CMAKE_GENERATOR      : Unix Makefiles
--   Compiler ID          : GNU
--   Build type           : Release
--   Build shared libs    : ON
--   Use double for kernel: OFF
--   Build tests          : ON
-- 
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
NVINFER
    linked by target "pointpillars" in directory /media/cavata/cavata/ubuntu_git/OpenPCdet/PointPillars_MultiHead_40FPS/pointpillars
    linked by target "test_model" in directory /media/cavata/cavata/ubuntu_git/OpenPCdet/PointPillars_MultiHead_40FPS/test

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

另外，我之前cmake ..没有出现此问题，但是在make时报错。

之后因为显卡驱动崩溃重装系统后，发现该cmake error

感谢您的帮助

**Comment by hova88** [comment]
> 我在安装Google-test后仍然存在cmake error
> 
> ```
> (openpcdet) cavata@cavata:~/project/OpenPCDet/PointPillars_MutilHead_40FPS/build $ cmake ..
> -- The C compiler identification is GNU 7.5.0
> -- The CXX compiler identification is GNU 7.5.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Found OpenMP_C: -fopenmp (found version "4.5") 
> -- Found OpenMP_CXX: -fopenmp (found version "4.5") 
> -- Found OpenMP: TRUE (found version "4.5")  
> Building tests
> -- Found Python: /home/cavata/anaconda3/envs/openpcdet/bin/python3.7 (found version "3.7.10") found components: Interpreter 
> -- 
> -- BUILD SUMMARY
> --   CMAKE_GENERATOR      : Unix Makefiles
> --   Compiler ID          : GNU
> --   Build type           : Release
> --   Build shared libs    : ON
> --   Use double for kernel: OFF
> --   Build tests          : ON
> -- 
> -- Configuring done
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> NVINFER
>     linked by target "pointpillars" in directory /media/cavata/cavata/ubuntu_git/OpenPCdet/PointPillars_MultiHead_40FPS/pointpillars
>     linked by target "test_model" in directory /media/cavata/cavata/ubuntu_git/OpenPCdet/PointPillars_MultiHead_40FPS/test
> 
> -- Generating done
> CMake Generate step failed.  Build files cannot be regenerated correctly.
> ```
> 
> 另外，我之前cmake ..没有出现此问题，但是在make时报错。
> 
> 之后因为显卡驱动崩溃重装系统后，发现该cmake error
> 
> 感谢您的帮助

奇怪，你cmake版本，显卡型号，nvcc版本都是多少？

**Comment by cagik** [comment]
我的cmake版本是3.21.0
显卡型号为 TITAN X(pascal) 驱动版本为Nvidia-driver-460
nvcc版本号为10.2
cudnn版本为8.0.2

**Comment by hova88** [comment]
> 我的cmake版本是3.21.0
> 显卡型号为 TITAN X(pascal) 驱动版本为Nvidia-driver-460
> nvcc版本号为10.2
> cudnn版本为8.0.2

虽然我不确定问题在哪，但我觉得问题不大😄。清空一下build目录，确定当下运行的版本和你cmakelist里面找到的NVINFER版本（也就是tensorrt，能找到应该都不会错吧）是否一致，会不会是之前生成的pointpillar动态库没有清理

**Comment by cagik** [comment]
好的，我自己再试一试，感谢您的帮助😄

**Comment by jcuic5** [comment]
我也遇到了该问题，FYI，可以在CMakeList里直接指定tensorrt library的位置：
```
set(CMAKE_PREFIX_PATH "/home/travis/packages/TensorRT-8.2.0.6/lib")
```

**Comment by hova88** [comment]
> 我也遇到了该问题，FYI，可以在CMakeList里直接指定tensorrt library的位置：
> 
> ```
> set(CMAKE_PREFIX_PATH "/home/travis/packages/TensorRT-8.2.0.6/lib")
> ```

对，安装环境不一致，多少会有些路径包含问题，这个优点耐心，能解决的
