### ISSUE TITLE
how to use this work on our own dataset

### ISSUE THREAD

**Issue by FreemanGong** [hova88/PointPillars_MultiHead_40FPS#16]
Our own dataset has been trained on openpcdet and I got the engine files. But I have trouble to understand the structure of this work. I will appreciate you if you could write a tutorial about how to run this work on our own dataset and then we could continue our research and cite your work on pointpillars.
Thanks for your useful work!

**Comment by hova88** [comment]
> Our own dataset has been trained on openpcdet and I got the engine files. But I have trouble to understand the structure of this work. I will appreciate you if you could write a tutorial about how to run this work on our own dataset and then we could continue our research and cite your work on pointpillars.
> Thanks for your useful work!

Thank you for your advice. I'll sort it out when I have time.

**Comment by FreemanGong** [comment]
Thanks for your reply! If the guidence have been finished, please send me the link of the work. 
My email is 794408089@qq.com. 
Thx!

**Comment by FreemanGong** [comment]
Our dataset has been made as KITTI dataset and finished the training process. We got .pth file of network, so if we want to use this work, where do we need to revise. if you have tried your work on KITTI dataset, we would appreciate it!

**Comment by jlqzzz** [comment]
@FreemanGong 

I have the same needs as you. If you succeed, can you share it with me?

My email is 1535655826@qq.com.

Thx!

**Comment by hova88** [comment]
> Our dataset has been made as KITTI dataset and finished the training process. We got .pth file of network, so if we want to use this work, where do we need to revise. if you have tried your work on KITTI dataset, we would appreciate it!

Try to use your own data! If not, even 50 hours to produce your own data, is way more important than 50 hours to study how to generalize with KITTI.
