### ISSUE TITLE
how to train custom dataset in MultiHead

### ISSUE THREAD

**Issue by qiuhui1991** [hova88/PointPillars_MultiHead_40FPS#2]

**Comment by hova88** [comment]
> _No description provided._

the MULTIHEAD right now, Specifically, the `postprocess.cu` is written pretty ugly. There still has so many details (or paraments) that need to be adjusted manually. so, if you want to custom your own dataset or model framework, you have to read my ugly code. or just waiting for me to make it beautiful.

**Comment by qiuhui1991** [comment]
thank you very much for your reply

**Comment by qiuhui1991** [comment]
> > _No description provided._
> 
> the MULTIHEAD right now, Specifically, the `postprocess.cu` is written pretty ugly. There still has so many details (or paraments) that need to be adjusted manually. so, if you want to custom your own dataset or model framework, you have to read my ugly code. or just waiting for me to make it beautiful.

i have complete custom dataset in single head, but i want to know how to transfor single head model to onnx, we need to change something in trans_backbone_multihead.py ?

**Comment by hova88** [comment]
> > > _No description provided._
> > 
> > 
> > the MULTIHEAD right now, Specifically, the `postprocess.cu` is written pretty ugly. There still has so many details (or paraments) that need to be adjusted manually. so, if you want to custom your own dataset or model framework, you have to read my ugly code. or just waiting for me to make it beautiful.
> 
> i have complete custom dataset in single head, but i want to know how to transfor single head model to onnx, we need to change something in trans_backbone_multihead.py ?

right. I think you need to modify `trans_backbone_multihead.py` and `onnx_dense_head.py`. 
1. try to define your singlehead framework in 'onnx_dense_head.py', 
2. use ‘trans_backbone_*.py` to do import/export stuff.

**Comment by qiuhui1991** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > the MULTIHEAD right now, Specifically, the `postprocess.cu` is written pretty ugly. There still has so many details (or paraments) that need to be adjusted manually. so, if you want to custom your own dataset or model framework, you have to read my ugly code. or just waiting for me to make it beautiful.
> > 
> > 
> > i have complete custom dataset in single head, but i want to know how to transfor single head model to onnx, we need to change something in trans_backbone_multihead.py ?
> 
> right. I think you need to modify `trans_backbone_multihead.py` and `onnx_dense_head.py`.
> 
>     1. try to define your singlehead framework in 'onnx_dense_head.py',
> 
>     2. use ‘trans_backbone_*.py` to do import/export stuff.

i confused to define singlehead in onnx_dense_head.py, can you give me example for singlehead framework?

**Comment by qiuhui1991** [comment]
> > > > > _No description provided._
> > > > 
> > > > 
> > > > the MULTIHEAD right now, Specifically, the `postprocess.cu` is written pretty ugly. There still has so many details (or paraments) that need to be adjusted manually. so, if you want to custom your own dataset or model framework, you have to read my ugly code. or just waiting for me to make it beautiful.
> > > 
> > > 
> > > i have complete custom dataset in single head, but i want to know how to transfor single head model to onnx, we need to change something in trans_backbone_multihead.py ?
> > 
> > 
> > right. I think you need to modify `trans_backbone_multihead.py` and `onnx_dense_head.py`.
> > ```
> > 1. try to define your singlehead framework in 'onnx_dense_head.py',
> > 
> > 2. use ‘trans_backbone_*.py` to do import/export stuff.
> > ```
> 
> i confused to define singlehead in onnx_dense_head.py, can you give me example for singlehead framework?

thank you for your project, i haved convert backbone_multihead.onnx and multihead_pfe.onnx succesfully in my custom dataset.

**Comment by hova88** [comment]
> > > > > > _No description provided._
> > > > > 
> > > > > 
> > > > > the MULTIHEAD right now, Specifically, the `postprocess.cu` is written pretty ugly. There still has so many details (or paraments) that need to be adjusted manually. so, if you want to custom your own dataset or model framework, you have to read my ugly code. or just waiting for me to make it beautiful.
> > > > 
> > > > 
> > > > i have complete custom dataset in single head, but i want to know how to transfor single head model to onnx, we need to change something in trans_backbone_multihead.py ?
> > > 
> > > 
> > > right. I think you need to modify `trans_backbone_multihead.py` and `onnx_dense_head.py`.
> > > ```
> > > 1. try to define your singlehead framework in 'onnx_dense_head.py',
> > > 
> > > 2. use ‘trans_backbone_*.py` to do import/export stuff.
> > > ```
> > 
> > 
> > i confused to define singlehead in onnx_dense_head.py, can you give me example for singlehead framework?
> 
> thank you for your project, i haved convert backbone_multihead.onnx and multihead_pfe.onnx succesfully in my custom dataset.

great! glad it has been useful to you. hope you enjoy your code.

**Comment by chinnikrishna55** [comment]
Hi, 

 Can you please provide changes needed to be done to convert the multihead to singlehead?

**Comment by Thomas-Kb** [comment]
> > > > > > _No description provided._
> > > > > 
> > > > > 
> > > > > the MULTIHEAD right now, Specifically, the `postprocess.cu` is written pretty ugly. There still has so many details (or paraments) that need to be adjusted manually. so, if you want to custom your own dataset or model framework, you have to read my ugly code. or just waiting for me to make it beautiful.
> > > > 
> > > > 
> > > > i have complete custom dataset in single head, but i want to know how to transfor single head model to onnx, we need to change something in trans_backbone_multihead.py ?
> > > 
> > > 
> > > right. I think you need to modify `trans_backbone_multihead.py` and `onnx_dense_head.py`.
> > > ```
> > > 1. try to define your singlehead framework in 'onnx_dense_head.py',
> > > 
> > > 2. use ‘trans_backbone_*.py` to do import/export stuff.
> > > ```
> > 
> > 
> > i confused to define singlehead in onnx_dense_head.py, can you give me example for singlehead framework?
> 
> thank you for your project, i haved convert backbone_multihead.onnx and multihead_pfe.onnx succesfully in my custom dataset.

Hi  @qiuhui1991, 
would you mind to share your onnx_dense_head.py?

**Comment by jlqzzz** [comment]
@hova88 @qiuhui1991 @Thomas-Kb @chasingw 

Has your single header version been successfully implemented?

Would you mind to share your onnx_dense_head.py and trans_backbone_singlehead.py ?
