### ISSUE TITLE
out_labels里的类别和out_detections里的包围盒不对应？

### ISSUE THREAD

**Issue by SayuZhang** [hova88/PointPillars_MultiHead_40FPS#21]
我把out_labels和out_detections按顺序一个个输出来，发现0有时候对应车有时候对应人，1,2,3也都不对。请问有人能解答一下吗？
0
41.2032  14.3038  -1.47437  4.50437  1.94559  1.63165  -0.153508  
1
12.2437  14.8986  -0.351534  4.54949  1.88161  1.63159  1.24538  
2
-5.04675  17.457  -0.105937  5.25686  2.03512  1.95156  -1.05545  
0
-6.78207  -28.2318  -1.11056  9.87344  2.89405  3.43961  1.47927  
0
-6.80986  26.5052  0.877446  4.09989  2.91479  3.26444  -0.217492  
0
9.53663  -10.7155  -1.62894  0.589162  3.18327  0.912035  -0.226208  
1
-4.21296  24.5938  -0.131519  0.430917  2.00643  1.07343  1.37179  
2
10.8363  -3.58328  -1.53543  0.575118  2.16364  1.07301  -0.0863243  
3
-0.491242  24.1164  -0.269451  0.365871  1.92069  1.03336  -1.34201  
4
5.36149  -26.1912  -2.10972  0.568812  3.08624  0.916287  -0.19608  
0
3.35874  15.7612  -0.448826  0.624788  0.628967  1.71421  0.635941  
1
3.62719  25.2403  0.230647  0.603434  0.634361  1.74347  -1.067  
2
4.49232  25.3182  0.191952  0.6769  0.664291  1.77158  0.533681

**Comment by hova88** [comment]
> 我把out_labels和out_detections按顺序一个个输出来，发现0有时候对应车有时候对应人，1,2,3也都不对。请问有人能解答一下吗？ 0 41.2032 14.3038 -1.47437 4.50437 1.94559 1.63165 -0.153508 1 12.2437 14.8986 -0.351534 4.54949 1.88161 1.63159 1.24538 2 -5.04675 17.457 -0.105937 5.25686 2.03512 1.95156 -1.05545 0 -6.78207 -28.2318 -1.11056 9.87344 2.89405 3.43961 1.47927 0 -6.80986 26.5052 0.877446 4.09989 2.91479 3.26444 -0.217492 0 9.53663 -10.7155 -1.62894 0.589162 3.18327 0.912035 -0.226208 1 -4.21296 24.5938 -0.131519 0.430917 2.00643 1.07343 1.37179 2 10.8363 -3.58328 -1.53543 0.575118 2.16364 1.07301 -0.0863243 3 -0.491242 24.1164 -0.269451 0.365871 1.92069 1.03336 -1.34201 4 5.36149 -26.1912 -2.10972 0.568812 3.08624 0.916287 -0.19608 0 3.35874 15.7612 -0.448826 0.624788 0.628967 1.71421 0.635941 1 3.62719 25.2403 0.230647 0.603434 0.634361 1.74347 -1.067 2 4.49232 25.3182 0.191952 0.6769 0.664291 1.77158 0.533681

我更新了后处理的代码，这个问题应该解决了...

不过我也没充分验证，不能打保票。
