### ISSUE TITLE
Broken nuscenes_10sweeps_points.txt link in README.md

### ISSUE THREAD

**Issue by Otteri** [hova88/PointPillars_MultiHead_40FPS#22]
Link to the nuscenes_10sweeps_points.txt data is broken. Link leads to google drive and gives an error "File is in owner's trash". 
Can the file be made downloadable again, so it's possible to follow steps in readme?

**Comment by hova88** [comment]
> Link to the nuscenes_10sweeps_points.txt data is broken. Link leads to google drive and gives an error "File is in owner's trash".
> Can the file be made downloadable again, so it's possible to follow steps in readme?

try this one . https://drive.google.com/file/d/1KD0LT0kzcpGUysUu__dfnfYnHUW62iwN/view?usp=sharing
