### ISSUE TITLE
Exporting the operator atan2 to ONNX opset version 10 is not supported.

### ISSUE THREAD

**Issue by speshowBUAA** [hova88/PointPillars_MultiHead_40FPS#26]
在pth转onnx的过程中，执行https://github.com/hova88/OpenPCDet里的python trans_backbone_multihead.py
报错Exporting the operator atan2 to ONNX opset version 10 is not supported.
请问有没有遇到类似的问题？该怎么处理？

**Comment by speshowBUAA** [comment]
我使用的环境是rtx3060, cuda 11.1, pytorch1.10.0

**Comment by immarioo** [comment]
你好，我也遇到了相同的问题，请问你怎么解决的？
