### ISSUE TITLE
由于需要使用TensorRT,需要对官方版本的网络进行一些客制化

### ISSUE THREAD

**Issue by qingxiali** [hova88/PointPillars_MultiHead_40FPS#29]
您好，请问在原版的训练代码中修改了哪里才可以转化为tensorrt，用最新的openPCDet v0.5.0训练的模型（cuda11.3,pytorch1.10,spconv2.1)可以用您这套c++代码部署吗？

**Comment by hova88** [comment]
> 您好，请问在原版的训练代码中修改了哪里才可以转化为tensorrt，用最新的openPCDet v0.5.0训练的模型（cuda11.3,pytorch1.10,spconv2.1)可以用您这套c++代码部署吗？

你好，我觉得应该是可以的。但是我没有follow v0.5 , 不确定最新的有那些修改，还是需要你自己过一下的，可以参考我那些commit做对应的修改。 （还有很多地方是可以优化的....）
