### ISSUE TITLE
singlehead onnx export

### ISSUE THREAD

**Issue by iloveai8086** [hova88/PointPillars_MultiHead_40FPS#31]
Hello everyone. In the hova88/openpcdet, i  can convert multihead-model to onnx. Can I convert a model of singlehead witch is trained with kitti format?

**Comment by hova88** [comment]
> Hello everyone. In the hova88/openpcdet, i can convert multihead-model to onnx. Can I convert a model of singlehead witch is trained with kitti format?

of course, but you should be clear about the corresponding calculation processing in `singlehead`

**Comment by cyhasuka** [comment]
> Hello everyone. In the hova88/openpcdet, i can convert multihead-model to onnx. Can I convert a model of singlehead witch is trained with kitti format?

@iloveai8086 Hello, I'm a beginner, and I've encountered the same issue as you. I currently have a pre-trained KITTI model (it should be a single-head one; I haven't figured out how to train a multi-head KITTI model yet), and I'm unable to run the code from this repository successfully using this model. Have you managed to implement this functionality? 
Thank you for offering your assistance.
