### ISSUE TITLE
unknown file: Failure C++ exception with description "bad file: ../bootstrap.yaml" thrown in the test body.

### ISSUE THREAD

**Issue by Leon-LiuY** [hova88/PointPillars_MultiHead_40FPS#32]
runtime log:
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from PointPillars
[ RUN      ] PointPillars.__build_model__
unknown file: Failure
C++ exception with description "bad file: ../bootstrap.yaml" thrown in the test body.
[  FAILED  ] PointPillars.__build_model__ (0 ms)
[----------] 1 test from PointPillars (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] PointPillars.__build_model__

 1 FAILED TEST

**Comment by hova88** [comment]
> runtime log: [==========] Running 1 test from 1 test suite. [----------] Global test environment set-up. [----------] 1 test from PointPillars [ RUN ] PointPillars.**build_model** unknown file: Failure C++ exception with description "bad file: ../bootstrap.yaml" thrown in the test body. [ FAILED ] PointPillars.**build_model** (0 ms) [----------] 1 test from PointPillars (0 ms total)
> 
> [----------] Global test environment tear-down [==========] 1 test from 1 test suite ran. (0 ms total) [ PASSED ] 0 tests. [ FAILED ] 1 test, listed below: [ FAILED ] PointPillars.**build_model**
> 
> 1 FAILED TEST

应该是路径问题，计算机没找到`../bootstrap.yaml`这个相对路径。确定相对路径启动是否正确，或者采用绝对路径替换。
