### ISSUE TITLE
my data is bin file,and i have converted bin file to txt file;I have compiled program succesfully with TensorRT, but the test failed

### ISSUE THREAD

**Issue by qiuhui1991** [hova88/PointPillars_MultiHead_40FPS#5]
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from PointPillars
[ RUN      ] PointPillars.__build_model__
./models/custom_data_multihead_backbone.trt
unknown file: Failure
C++ exception with description "bad file: ./pointpillars/cfgs/pointpillar_sanyi_multi.yaml" thrown in the test body.
[  FAILED  ] PointPillars.__build_model__ (1 ms)
[----------] 1 test from PointPillars (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (1 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] PointPillars.__build_model__

 1 FAILED TEST

**Comment by hova88** [comment]
`./pointpillars/cfgs/pointpillar_sanyi_multi.yaml` --> '../pointpillars/cfgs/pointpillar_sanyi_multi.yaml'

**Comment by qiuhui1991** [comment]
> `./pointpillars/cfgs/pointpillar_sanyi_multi.yaml` --> '../pointpillars/cfgs/pointpillar_sanyi_multi.yaml'

I tried the absolute path, but I still reported an error.

[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from PointPillars
[ RUN      ] PointPillars.__build_model__
/media/projects/ly/TensorRT-pointpillars/PointPillars_MultiHead_40FPS/models/custom_data_multihead_backbone.trt
unknown file: Failure
C++ exception with description "bad conversion" thrown in the test body.
[  FAILED  ] PointPillars.__build_model__ (7 ms)
[----------] 1 test from PointPillars (7 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (7 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] PointPillars.__build_model__

 1 FAILED TEST

**Comment by qiuhui1991** [comment]
thank you for your reply,I have find the problem,duo to pointpillar_multi.yaml file dont append BOX_CODER_CONFIG: {
                'code_size': 9,
                'encode_angle_by_sincos': True
            }
in TARGET_ASSIGNER_CONFIG,
and when I append BOX_CODER_CONFIG: {
                'code_size': 9,
                'encode_angle_by_sincos': True
            } in TARGET_ASSIGNER_CONFIG, i can not train my customer dataset , show the error 
RuntimeError: shape mismatch: value tensor of shape [21, 8] cannot be broadcast to indexing result of shape [21, 9]
I want to know how to append BOX_CODER_CONFIG: {
                'code_size': 9,
                'encode_angle_by_sincos': True
            } in my customer dataset?

**Comment by hova88** [comment]
> thank you for your reply,I have find the problem,duo to pointpillar_multi.yaml file dont append BOX_CODER_CONFIG: {
> 'code_size': 9,
> 'encode_angle_by_sincos': True
> }
> in TARGET_ASSIGNER_CONFIG,
> and when I append BOX_CODER_CONFIG: {
> 'code_size': 9,
> 'encode_angle_by_sincos': True
> } in TARGET_ASSIGNER_CONFIG, i can not train my customer dataset , show the error
> RuntimeError: shape mismatch: value tensor of shape [21, 8] cannot be broadcast to indexing result of shape [21, 9]
> I want to know how to append BOX_CODER_CONFIG: {
> 'code_size': 9,
> 'encode_angle_by_sincos': True
> } in my customer dataset?

试试这个？
```
BOX_CODER_CONFIG: {
'code_size': 8,
'encode_angle_by_sincos': True
} 
```
不过，朋友，这个还不是一个完备的工程级代码，就算你解决了这个问题，我想后面还会有很多小的细节坑等着你。
我觉得这个代码的价值是给你提供一个思路和基本框架，你可以试着在我的基础上，自己写一个适合你使用的推理模型。

**Comment by qiuhui1991** [comment]
> > thank you for your reply,I have find the problem,duo to pointpillar_multi.yaml file dont append BOX_CODER_CONFIG: {
> > 'code_size': 9,
> > 'encode_angle_by_sincos': True
> > }
> > in TARGET_ASSIGNER_CONFIG,
> > and when I append BOX_CODER_CONFIG: {
> > 'code_size': 9,
> > 'encode_angle_by_sincos': True
> > } in TARGET_ASSIGNER_CONFIG, i can not train my customer dataset , show the error
> > RuntimeError: shape mismatch: value tensor of shape [21, 8] cannot be broadcast to indexing result of shape [21, 9]
> > I want to know how to append BOX_CODER_CONFIG: {
> > 'code_size': 9,
> > 'encode_angle_by_sincos': True
> > } in my customer dataset?
> 
> 试试这个？
> 
> ```
> BOX_CODER_CONFIG: {
> 'code_size': 8,
> 'encode_angle_by_sincos': True
> } 
> ```
> 
> 不过，朋友，这个还不是一个完备的工程级代码，就算你解决了这个问题，我想后面还会有很多小的细节坑等着你。
> 我觉得这个代码的价值是给你提供一个思路和基本框架，你可以试着在我的基础上，自己写一个适合你使用的推理模型。

谢谢你的提醒，这个问题为已经解决了，但是又遇到了新的问题，
ERROR: ../rtSafe/cuda/genericReformat.cu (1294) - Cuda Error in executeMemcpy: 1 (invalid argument)
ERROR: FAILED_EXECUTION: std::exception
GPUassert: an illegal memory access was encountered /media/PointPillars_MultiHead_40FPS/pointpillars/postprocess.cu 433
这个问题你以前遇到过吗？
