### ISSUE TITLE
thank you for your project,I've completely run through the algorithm on my own dataset.

### ISSUE THREAD

**Issue by qiuhui1991** [hova88/PointPillars_MultiHead_40FPS#7]
------------------------------------
Module        Time        
------------------------------------
Preprocess    0.44171  ms
Pfe           12.0893  ms
Scatter       0.118499 ms
Backbone      2.84478  ms
Postprocess   39.299   ms
Summary       54.8017  ms
------------------------------------
num_objects----------------------------
2000
[       OK ] PointPillars.__build_model__ (850 ms)
[----------] 1 test from PointPillars (850 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (850 ms total)
[  PASSED  ] 1 test.

**Comment by iceriver97** [comment]
您好, 请问您有遇到下面的问题吗?
```
(yolop) li@li:~/project/OpenPCDet/PointPillars_MultiHead_40FPS/build$ ./test/test_model 
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from PointPillars
[ RUN      ] PointPillars.__build_model__
unknown file: Failure
C++ exception with description "yaml-cpp: error at line 0, column 0: bad file" thrown in the test body.
```

**Comment by Nan1chen** [comment]
> 您好, 请问您有遇到下面的问题吗?
> 
> ```
> (yolop) li@li:~/project/OpenPCDet/PointPillars_MultiHead_40FPS/build$ ./test/test_model 
> [==========] Running 1 test from 1 test suite.
> [----------] Global test environment set-up.
> [----------] 1 test from PointPillars
> [ RUN      ] PointPillars.__build_model__
> unknown file: Failure
> C++ exception with description "yaml-cpp: error at line 0, column 0: bad file" thrown in the test body.
> ```

请问您解决了吗，我也遇到了同样的问题
