### ISSUE TITLE
the inference in my computer is very slow, can you give me some suggestions?

### ISSUE THREAD

**Issue by qiuhui1991** [hova88/PointPillars_MultiHead_40FPS#8]
------------------------------------
Module        Time        
------------------------------------
Preprocess    0.440277 ms
Pfe           13.8402  ms
Scatter       0.11535  ms
Backbone      348.759  ms
Postprocess   40.2281  ms
Summary       403.392  ms
------------------------------------
num_objects----------------------------

**Comment by hova88** [comment]
啊....这个我也不知道，首先你先确定你的结果是否正确，backbone怎么也不应该300+ms,是不是有保存操作

**Comment by qiuhui1991** [comment]
> 啊....这个我也不知道，首先你先确定你的结果是否正确，backbone怎么也不应该300+ms,是不是有保存操作
谢谢，为已经解决了这个问题，用fp16 推理，速度降到了10ms,但是预测结果不正确，我的 RPN_HEAD_CFGS: [
            {
                'HEAD_CLS_NAME': [ 'vehicle' ],
            },
            {
                'HEAD_CLS_NAME': [ 'car' ],
            },
            {
                'HEAD_CLS_NAME': [ 'pedestrian'],
            },
            {
                'HEAD_CLS_NAME': [ 'cyclist' ],
            },
        ]
不知道从哪里修改代码，麻烦指导一下,多谢
