### ISSUE TITLE
Nvidia Jetson devices support!

### ISSUE THREAD

**Issue by YoushaaMurhij** [hova88/PointPillars_MultiHead_40FPS#9]
Great work! have you tested this model on Jetson devices like TX2 or Xavier ? or Do you have any plan to implement it in the future ?

**Comment by hova88** [comment]
> Great work! have you tested this model on Jetson devices like TX2 or Xavier ? or Do you have any plan to implement it in the future ?

Yep, I tested it on Xavier. As long as the environment is consistent (TensorRT 7.1.0+，CUDA 10.2, onnx2trt ), running this repo is basically no problem. But you need to note that there are many imperfections that you need to improve.
